### ISSUE TITLE
Feature Request: unblock

### ISSUE THREAD

**Issue by temujin9** [myConsciousness/atproto.dart#992]
## Packages/Tools
- [ ] **bluesky_cli**

## Proposal
- an unblock command similar to the unmute command

## Risks
- none I can foresee

**Comment by temujin9** [comment]
This is functionally equivalent to a delete on the appropriate "blocking" at uri; it can be accomplished with that in the mean time.

**Comment by myConsciousness** [comment]
Hi @temujin9 !

A block in Bluesky is represented as an atproto `record`, this is the same as post and follow. So, since atproto supports a `deleteRecord` endpoint (`delete` command on `bluesky_cli`) that can delete all records based on AT URIs with a common mechanism, there seems to me no need to implement `unfollow` or `unblock`.

A possible use case for deleting blocks with `bluesky_cli` is to use the `blocks` command to get a list of blocks and then delete a specific block. Then this list contains the AT URI for the block, so we could remove the block as follows :)

```bash
bsky delete --uri=at://........
```

**Comment by temujin9** [comment]
Yep, I've had luck with that. This is mostly just for parity with the mute / unmute functionality; feel free to close it if not useful to you.
